{% set name = "HepMC3" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://hepmc.web.cern.ch/hepmc/releases/{{ name  }}-{{ version }}.tar.gz
  sha256: 07b4ce3fd96d8741bf6034e564dc4c6517449f23a33c9c50c5ec81dc6db9b300
  folder: source

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  source_files:
    - source/test
  requires:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  commands:
    # Workaround for lack of CONDA_BUILD_SYSROOT variable in staged recipes
    - export CONDA_BUILD_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk  # [osx]
    - cd source/test
    - ${CXX} -std=c++11 testMass.cc -o testMass.exe -I${CONDA_PREFIX}/include -L${CONDA_PREFIX}/lib -lHepMC3
      # Fix up the runpath
    - ${INSTALL_NAME_TOOL} -change @rpath/libHepMC3.3.dylib $CONDA_PREFIX/lib/libHepMC3.dylib testMass.exe  # [osx]
    - ./testMass.exe

about:
  home: https://hepmc.web.cern.ch/hepmc/
  license: GPL-3
  license_family: GPL
  license_file: source/LICENCE
  summary: HepMC3 is a new rewrite of HepMC event record.
  description: |
    HepMC3 is a new rewrite of HepMC event record. It uses shared pointers
    for in-memory navigation and the POD concept for the persistency.
  dev_url: https://gitlab.cern.ch/hepmc/HepMC3

extra:
  recipe-maintainers:
    - henryiii
    - chrisburr
    - gartung
