{% set name = "HepMC3" %}
{% set version = "3.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  url: https://hepmc.web.cern.ch/hepmc/releases/{{ name }}-{{ version }}.tar.gz 
  sha256: 587faa6556cc54ccd89ad35421461b4761d7809bc17a2e72f5034daea142232b 
  folder: source

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - zlib
    - bzip2

test:
  source_files:
    - source/test
  requires:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  commands:
    # Workaround for lack of CONDA_BUILD_SYSROOT variable in staged recipes
    - export CONDA_BUILD_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk  # [osx]
    - cd source/test
    - ${CXX} -std=c++11 testMass.cc -o testMass.exe -I${CONDA_PREFIX}/include -L${CONDA_PREFIX}/lib -lHepMC3
      # Fix up the runpath
    - ${INSTALL_NAME_TOOL} -change @rpath/libHepMC3.3.dylib $CONDA_PREFIX/lib/libHepMC3.dylib testMass.exe  # [osx]
    - ./testMass.exe

about:
  home: https://hepmc.web.cern.ch/hepmc/
  license: GPL-3.0-or-later
  license_file: source/COPYING
  summary: HepMC3 is a new rewrite of HepMC event record.
  description: |
    HepMC3 is a new rewrite of HepMC event record. It uses shared pointers
    for in-memory navigation and the POD concept for the persistency.
  dev_url: https://gitlab.cern.ch/hepmc/HepMC3

extra:
  recipe-maintainers:
    - henryiii
    - chrisburr
    - gartung
